export const projects = [
  {
    slug: "skillforge-ai",
    name: "SkillForge AI",
    imageLabel: "AI Career Learning Platform",
    screenshot: "/skillforge-ai/skillforge-01-home.png",
    screenshots: [
      "/skillforge-ai/skillforge-01-home.png",
      "/skillforge-ai/skillforge-02-dashboard.png",
      "/skillforge-ai/skillforge-03-roadmap-builder.png",
      "/skillforge-ai/skillforge-04-ai-mentor.png",
      "/skillforge-ai/skillforge-05-interview-practice.png",
      "/skillforge-ai/skillforge-06-project-workspace.png",
    ],
    screenshotLabels: ["Home", "Learner Dashboard", "AI Roadmap Builder", "AI Mentor (LLM)", "Interview Practice", "Project Workspace"],
    liveLink: "https://skillforge-ai-client.vercel.app/",
    githubLink: "https://github.com/FBushra-git/SCIC-Assignment-05-Client",
    serverGithubLink: "https://github.com/FBushra-git/SCIC-Assignment-05-Server",
    stack: [
      "Next.js 16",
      "React 19",
      "TypeScript",
      "Tailwind CSS 4",
      "TanStack Query",
      "Better Auth",
      "Express 5",
      "MongoDB",
      "Google Gemini API",
      "React Hook Form",
      "Zod",
      "Recharts",
      "Framer Motion",
    ],
    shortDescription: "An AI-powered career workspace for personalized roadmaps, mentor guidance, progress, projects, and interview practice.",
    description:
      "SkillForge AI is a full-stack career planning and learning workspace for students, graduates, and self-directed learners. It combines personalized learner profiles with Gemini-powered roadmap generation, progress analytics, portfolio projects, interview practice, public learning resources, and a context-aware AI mentor.",
    purpose:
      "The platform turns a learner's career goal, current skills, experience, study availability, and learning preferences into an actionable development plan. It keeps planning, hands-on practice, progress tracking, and AI guidance in one secure workspace instead of splitting the learning journey across disconnected tools.",
    purposePoints: [
      "Generate structured career roadmaps with progressive phases and weekly milestones",
      "Ground AI mentor answers in the learner profile, roadmap progress, and prior messages",
      "Track completed lessons, learning streaks, saved projects, and interview sessions",
      "Let visitors explore public roadmaps, resources, articles, and learner-created project briefs",
      "Protect learner-owned content and account workspaces with server-validated sessions",
      "Surface personalized next actions from goals, skills, weak areas, and project state",
    ],
    features: [
      "Personalized career profiles for goals, skills, experience, availability, and learning preferences",
      "Gemini-powered roadmap generation with phases, milestones, resources, projects, and interview checkpoints",
      "Persistent roadmap progress, completion controls, learning streaks, and Recharts analytics",
      "Context-aware AI mentor with conversation history, Markdown, code blocks, and suggested prompts",
      "AI interview question generation with sessions, bookmarks, completion tracking, and history",
      "Public roadmap discovery with search, simultaneous filters, sorting, pagination, and detail pages",
      "Project library with saved status, detailed outcomes, progress controls, and related recommendations",
      "Complete ownership-protected project-item CRUD with public listing and details routes",
      "Email/password, Google OAuth, and demo authentication powered by Better Auth",
      "Validated newsletter, contact, and account-recovery flows with responsive light and dark themes",
    ],
    challenges:
      "The most demanding part was coordinating several data-rich AI workflows without losing user context. Roadmap output, mentor conversations, recommendations, and interview practice all depend on profile and progress data, while authentication cookies, ownership checks, Zod validation, rate limits, and API error states must remain consistent across the Next.js client and modular Express server.",
    improvements:
      "Future plans include richer roadmap versioning, more detailed skill-gap analytics, broader AI model fallback options, mentor response citations, expanded interview scoring, collaborative learning groups, and stronger automated coverage for long-running AI and progress workflows.",
  },
  {
    slug: "crowdspark",
    name: "CrowdSpark",
    imageLabel: "Crowdfunding Platform",
    screenshot: "/crowdspark/crowdspark-01-home.png",
    screenshots: [
      "/crowdspark/crowdspark-01-home.png",
      "/crowdspark/crowdspark-02-campaign-explorer.png",
      "/crowdspark/crowdspark-03-supporter-dashboard.png",
      "/crowdspark/crowdspark-04-creator-dashboard.png",
      "/crowdspark/crowdspark-05-admin-dashboard.png",
      "/crowdspark/crowdspark-06-admin-campaigns.png",
    ],
    screenshotLabels: ["Home", "Campaign Explorer", "Supporter Dashboard", "Creator Dashboard", "Admin Dashboard", "Campaign Moderation"],
    liveLink: "https://crowdspark-client-side.vercel.app/",
    githubLink: "https://github.com/FBushra-git/CrowdSpark-Client-Side",
    serverGithubLink: "https://github.com/FBushra-git/CrowdSpark-Server-Side",
    stack: [
      "Next.js 16",
      "React 19",
      "TypeScript",
      "Tailwind CSS 4",
      "Express 5",
      "MongoDB",
      "Mongoose",
      "JWT",
      "Google OAuth",
      "React Hook Form",
      "Zod",
      "Axios",
      "Recharts",
      "Framer Motion",
      "Stripe SDK",
    ],
    shortDescription: "A production-style crowdfunding platform with campaigns, credit contributions, role dashboards, and admin moderation.",
    description:
      "CrowdSpark is a full-stack crowdfunding platform with distinct experiences for supporters, campaign creators, and administrators. Visitors can discover approved campaigns, supporters can purchase and contribute credits, creators can manage campaigns and contribution decisions, and admins can moderate campaigns, users, reports, and withdrawals.",
    purpose:
      "The project models a complete funding workflow rather than a simple CRUD dashboard. It focuses on transparent campaign discovery, secure role-based actions, auditable credit movement, creator approval queues, withdrawal rules, notifications, analytics, and platform governance across a Next.js client and Express API.",
    purposePoints: [
      "Give supporters a searchable and transparent way to discover approved campaigns",
      "Model contributions as reviewable credit transactions with approval and refund states",
      "Provide creators with campaign management, performance data, and withdrawal controls",
      "Give administrators operational tools for campaign, user, report, and withdrawal moderation",
      "Restore JWT sessions and protect role-specific dashboard routes and API actions",
      "Keep users informed through persistent notifications and transaction history",
    ],
    features: [
      "Public campaign explorer with search, category and funding filters, deadline filters, sorting, pagination, and loading states",
      "Campaign details with story, reward information, progress, creator data, and contribution entry points",
      "Email/password registration, Google login, JWT persistence, session restoration, and role-aware navigation",
      "Supporter credit purchase flow with contribution history, payment history, statistics, and notifications",
      "Creator campaign drafts, updates, performance stats, contribution approval or rejection, and withdrawal requests",
      "Admin campaign approval, rejection, and suspension plus user, report, withdrawal, and flagged-content management",
      "Server-side role authorization, bcrypt password hashing, Google ID-token verification, and Zod request validation",
      "MongoDB and Mongoose models for users, campaigns, contributions, payments, withdrawals, notifications, and reports",
      "Image upload endpoint using Multer memory storage and the imgBB API",
      "Responsive dark-mode-ready dashboards with Recharts analytics, Framer Motion, Swiper, Sonner, and Lucide icons",
    ],
    challenges:
      "The core challenge was preserving financial-style consistency across several asynchronous state transitions. A contribution deducts supporter credits while pending, creator approval moves credits into campaign and creator totals, rejection refunds the supporter, and withdrawals require balance and threshold validation before admin review. Every transition also needs role authorization, history, and notifications.",
    improvements:
      "Future plans include completing a production Stripe checkout instead of the current credit-purchase simulation, adding email delivery for all notification events, expanding fraud and campaign-risk signals, introducing richer creator analytics, and adding automated integration tests around contribution refunds and withdrawal state changes.",
  },
  {
    slug: "promptrix",
    name: "Promptrix",
    imageLabel: "AI Prompt Marketplace",
    screenshot: "/promptrix/promptrix1.jpeg",
    screenshots: [
      "/promptrix/promptrix1.jpeg",
      "/promptrix/promptrix2.jpeg",
      "/promptrix/promptrix3.jpeg",
      "/promptrix/promptrix4.jpeg",
      "/promptrix/promptrix5.jpeg",
    ],
    liveLink: "https://promptrix-client.vercel.app/",
    githubLink: "https://github.com/FBushra-git/promptrix-client-side",
    stack: ["Next.js", "React", "MongoDB", "Better Auth", "Stripe", "Tailwind CSS", "React Hot Toast", "Framer Motion"],
    shortDescription: "An AI prompt marketplace with creator workflows, premium access, and admin moderation.",
    description:
      "Promptrix is an AI prompt marketplace built with Next.js and MongoDB. It enables prompt creators to submit and manage AI prompts, while users can browse, bookmark, review, and unlock premium content. Admins moderate prompts, approve or reject submissions, and manage users.",
    purpose:
      "This project was created to demonstrate a modern creator marketplace with creator submission workflows, premium access control, role-based access, real-time prompt analytics, secure Better Auth authentication, and media upload support for prompt thumbnails.",
    purposePoints: [
      "Creator submission workflow",
      "Premium access control",
      "Role-based access for users, creators, and admins",
      "Real-time prompt analytics",
      "Secure authentication with Better Auth",
      "Media upload support for prompt thumbnails",
    ],
    features: [
      "Creator prompt submission with thumbnail upload",
      "Public and private prompt visibility modes",
      "Prompt approval workflow for admin moderation",
      "Premium subscription unlock for private prompts",
      "Prompt bookmarking, reviews, and reporting",
      "Creator dashboard with analytics and performance metrics",
      "Role-based navigation and access control",
      "Stripe-based premium purchase flow",
      "Search, filtering, sorting, and pagination for prompt browsing",
    ],
    challenges:
      "The main challenge was coordinating several product roles and states in one marketplace: public users, prompt creators, premium members, and admins all needed different access levels, dashboards, and moderation flows.",
    improvements:
      "Future improvements include richer creator insights, more advanced recommendation logic, additional premium plans, stronger reporting tools, and deeper content quality controls for admins.",
  },
  {
    slug: "petnest",
    name: "PetNest",
    imageLabel: "Pet Adoption Platform",
    screenshot: "/petnest/petnest1.jpeg",
    screenshots: [
      "/petnest/petnest1.jpeg",
      "/petnest/petnest2.jpeg",
      "/petnest/petnest3.jpeg",
      "/petnest/petnest4.jpeg",
    ],
    liveLink: "https://pet-adoption-three-indol.vercel.app/",
    githubLink: "https://github.com/FBushra-git/Assignment-09-client-side",
    stack: ["Next.js", "React", "MongoDB", "JWT", "Tailwind CSS", "Toast Notifications", "Responsive Design"],
    shortDescription: "A full-stack pet adoption platform with pet listings, adoption requests, dashboards, and secure private routes.",
    description:
      "PetNest is a full-stack pet adoption platform built with Next.js, MongoDB, authentication, and secure backend APIs. Users can browse pets, view detailed pet profiles, and submit adoption requests, while pet owners can manage listings and handle adoption decisions.",
    purpose:
      "This project was created to model a real-world pet adoption portal where users, pet owners, and shelters can manage the adoption flow from discovery to request approval in a clean, recruiter-friendly interface.",
    purposePoints: [
      "Browse available pets by category and details",
      "Submit adoption requests from protected routes",
      "Allow owners to add, update, and delete pet listings",
      "Approve or reject adoption requests from a dashboard",
      "Protect private pages with secure authentication",
      "Store and manage pet and request data in MongoDB",
    ],
    features: [
      "Home page with hero, featured pets, adoption reasons, success stories, and pet care sections",
      "All Pets page with pet cards and details navigation",
      "Authentication with login, registration, password validation, and Google login support",
      "Private dashboard routes for My Requests, Add Pet, and My Listings",
      "Add Pet form with species, breed, age, gender, image, health, location, fee, and description fields",
      "Pet details page with adoption request form and pending request status",
      "Owner listing management with request modal, edit, view, and delete actions",
      "Search, filtering, and sorting support for browsing pets",
      "JWT authentication with protected private routes and secure API access",
      "Toast-based feedback, loading states, custom not-found page, and responsive design",
    ],
    challenges:
      "A key challenge was managing the adoption workflow across different user roles while keeping private route reloads stable, protecting owner-only actions, and preventing pet owners from requesting adoption for their own pets.",
    improvements:
      "Future improvements include richer pet discovery filters, wishlist support, dark/light theme polish, more detailed owner analytics, server-side moderation tools, and stronger adoption status automation.",
  },
  {
    slug: "tiles-gallery",
    name: "Tiles Gallery",
    imageLabel: "Gallery Interface",
    screenshot: "/Tiles gallery/tiles1.jpeg",
    screenshots: [
      "/Tiles gallery/tiles1.jpeg",
      "/Tiles gallery/tiles2.jpeg",
      "/Tiles gallery/tiles3.jpeg",
      "/Tiles gallery/tiles4.jpeg",
      "/Tiles gallery/tiles5.jpeg",
    ],
    liveLink: "https://assignment-08-tiles-gallery-iota.vercel.app/",
    githubLink: "https://assignment-08-tiles-gallery-iota.vercel.app/",
    stack: ["Next.js", "React", "MongoDB", "Better Auth", "DaisyUI / HeroUI", "SwiperJS", "Responsive Design"],
    shortDescription: "A Next.js tile gallery for browsing tile collections, viewing details, and managing profile access.",
    description:
      "Tiles Gallery is a Next.js App Router website built to showcase tile collections through a polished gallery interface. Users can browse all tiles, search by title, view high-resolution tile details, authenticate with email or Google, and access private profile features.",
    purpose:
      "This project was created to demonstrate a modern tile gallery experience with responsive browsing, secure authentication, protected detail/profile routes, and product-style tile presentation.",
    purposePoints: [
      "Showcase tile collections with strong visual focus",
      "Use Next.js App Router for public and private routes",
      "Support authentication with Better Auth and MongoDB",
      "Allow users to search tiles by title",
      "Display tile details with large image preview and product information",
      "Provide a private My Profile route with update capability",
    ],
    features: [
      "Home page with banner, marquee, and featured tiles section",
      "All Tiles page with search input and tile cards",
      "Single tile details page with large preview, title, creator, style description, and tags",
      "Login and registration pages with form validation and Google social login",
      "Private My Profile route for logged-in user data",
      "Profile update flow for name and image URL",
      "Responsive design for mobile, tablet, and desktop",
      "Loader states, custom not-found page, and safe route reload behavior",
      "Tile data structure with title, description, image, category, price, dimensions, material, and stock status",
      "SwiperJS/animation package support for a richer gallery experience",
    ],
    challenges:
      "The main challenge was combining an image-heavy product gallery with route permissions, authentication, search, and detail pages while keeping the layout clean and responsive across devices.",
    improvements:
      "Future improvements include richer category filtering, saved tile collections, image zoom, inquiry forms, admin tile management, and a dynamic content dashboard for maintaining the gallery.",
  },
  {
    slug: "keenkeeper",
    name: "KeenKeeper",
    imageLabel: "Friendship Tracker",
    screenshot: "/keenkeeper/keen1.jpeg",
    screenshots: [
      "/keenkeeper/keen1.jpeg",
      "/keenkeeper/keen2.jpeg",
      "/keenkeeper/keen3.jpeg",
      "/keenkeeper/keen4.jpeg",
      "/keenkeeper/keen5.jpeg",
    ],
    liveLink: "https://keenkeeper-bushra.netlify.app/",
    githubLink: "https://github.com/FBushra-git/Assignment-07",
    stack: ["Next.js", "React", "Tailwind CSS", "Recharts", "Toast Notifications", "Responsive Design"],
    shortDescription: "A friendship tracking app with friend cards, detail pages, timeline logging, and analytics.",
    description:
      "KeenKeeper is a friendship tracker built to help users stay connected with important people. The app displays friend profiles, tracks days since last contact, highlights relationship status, logs call/text/video check-ins, and visualizes interaction history through timeline and analytics views.",
    purpose:
      "This project was created to practice building a multi-page relationship management dashboard with clean navigation, realistic JSON data, interactive check-in actions, timeline state updates, toast feedback, and responsive analytics UI.",
    purposePoints: [
      "Track days since last contact for each friend",
      "Show status-based friend cards for overdue, almost due, and on-track relationships",
      "Provide friend detail pages with profile information and quick actions",
      "Log call, text, and video interactions into a timeline",
      "Visualize interaction counts with a Recharts pie chart",
      "Keep the layout responsive across mobile, tablet, and desktop screens",
    ],
    features: [
      "Navbar with logo, icon links, and active link highlighting",
      "Centered banner with subtitle, Add a Friend action, and four summary cards",
      "Friend data loaded from a JSON file with realistic profiles, tags, goals, and next due dates",
      "Four-column friend card grid on large screens with status-based colors",
      "Friend detail page with profile card, stats cards, relationship goal, and quick check-in actions",
      "Call, Text, and Video buttons that add timeline entries and show toast notifications",
      "Timeline page with dated interaction entries and type-specific icons",
      "Timeline filters for Call, Text, and Video interactions",
      "Friendship Analytics page with Recharts pie chart for interaction counts",
      "Loading animation, custom 404 page, responsive footer, and route-safe reload behavior",
    ],
    challenges:
      "The main challenge was coordinating shared interaction state across friend details, timeline, and analytics while keeping the UI aligned with the Figma-style layout and responsive on different screen sizes.",
    improvements:
      "Future improvements include persistent backend storage, friend search, timeline sorting by newest or oldest, editable friend goals, richer reminders, and authentication for personal friendship data.",
  },
];






